import {
  FB_API_KEY,
  FB_AUTH_DOMAIN,
  FB_STORAGEBUCKET,
  FB_MESSAGING_ID,
  FB_APP_ID,
  FB_MEASUREMENT_ID,
  FB_PROJECT_ID,
  RAPID_API_KEY,
} from "@env";

export default {
  FB_API_KEY,
  FB_AUTH_DOMAIN,
  FB_STORAGEBUCKET,
  FB_MESSAGING_ID,
  FB_APP_ID,
  FB_MEASUREMENT_ID,
  FB_PROJECT_ID,
  RAPID_API_KEY,
};
